apiVersion: dbaas.redhat.com/v1alpha1
kind: DBaaSInstance
metadata:
  name: test-dbaas-instance-crdb
spec:
  inventoryRef:
    name: crdb-inventory
    namespace: openshift-dbaas-operator
  provisioningParameters:
    name: my-crdb-dedicated
    plan: DEDICATED
    cloudProvider: AWS
    regions: us-east-1
    nodes: "3"
    machineType: m5.large
    storageGib: "0"
