apiVersion: dbaas.redhat.com/v1alpha1
kind: DBaaSInstance
metadata:
  name: dbaasinstance-sample
spec:
  inventoryRef:
    name: atlas-inventory
    namespace: openshift-dbaas-operator
  name: my-cluster-free
  cloudProvider: AWS
  cloudRegion: US_EAST_1
  otherInstanceParams:
    projectName: my-atlas-project-free
    instanceSizeName: M0
